# GitHub Pages Configuration

# Plugins (GitHub Pages automatically includes these)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Site settings
title: "NerdPioneer - Ezekiel Obeisun Jr"
description: "Cybersecurity Analyst Portfolio showcasing professional experience, certifications, and security projects"
url: "https://nerdpioneer.github.io"
baseurl: ""

# Author information
author:
  name: "Ezekiel Obeisun Jr"
  email: "ezekiel.obeisun@email.com"

# Social media
social:
  github: "NerdPioneer"
  linkedin: "ezekiel-obeisun"
  medium: "nerdpioneer"
  medium_url: "https://medium.com/@nerdpioneer"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Exclude from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - .github/

# Include files
include:
  - _pages

# Collections (if needed for blog posts later)
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# SEO settings
lang: en_US
image: /assets/images/social-share.png
